import sys

reverseChar = dict()
'''
reverseChar['A'] = 'A'
reverseChar['H'] = 'H'
reverseChar['I'] = 'I'
reverseChar['M'] = 'M'
reverseChar['O'] = 'O'
reverseChar['T'] = 'T'
reverseChar['U'] = 'U'
reverseChar['V'] = 'V'
reverseChar['W'] = 'W'
reverseChar['X'] = 'X'
reverseChar['Y'] = 'Y'
reverseChar['o'] = 'o'
reverseChar['v'] = 'v'
reverseChar['w'] = 'w'
reverseChar['x'] = 'x'
reverseChar['0'] = '0'
reverseChar['8'] = '8'
reverseChar['.'] = '.'
reverseChar['b'] = 'd'
reverseChar['d'] = 'b'
reverseChar['p'] = 'q' 
reverseChar['q'] = 'p'
reverseChar['B'] = u'\u0A98'
reverseChar['C'] = u'\u0186'
reverseChar['D'] = u'\u15E1'
reverseChar['E'] = u'\u018E'
reverseChar['F'] = u'\u15B7'
reverseChar['G'] = u'\u1610'
reverseChar['J'] = u'\u0546'
reverseChar['K'] = u'\uFEFC'
reverseChar['L'] = u'\u2143'
reverseChar['N'] = u'\u0418'
reverseChar['P'] = u'\uA7FC'
reverseChar['Q'] = u'\u03D8'
reverseChar['R'] = u'\u042F'
reverseChar['S'] = u'\u01A7'
reverseChar['Z'] = u'\uFEDB'
'''

reverseChar['a'] = u'\u0252'
reverseChar['c'] = u'\u0254'
#reverseChar['f'] = u'\u13B8'
reverseChar['f'] = u'\u0287'
reverseChar['e'] = u'\u0258'

'''
reverseChar['g'] = u'\u'
reverseChar['h'] = u'\u'
reverseChar['i'] = u'\u'
reverseChar['j'] = u'\u'
reverseChar['k'] = u'\u'
reverseChar['l'] = u'\u'
reverseChar['m'] = u'\u'
reverseChar['n'] = u'\u'
reverseChar['r'] = u'\u'
reverseChar['s'] = u'\u'
reverseChar['t'] = u'\u'
reverseChar['u'] = u'\u'
reverseChar['y'] = u'\u'
reverseChar['z'] = u'\u'
reverseChar['1'] = u'\u'
reverseChar['2'] = u'\u'
reverseChar['3'] = u'\u'
reverseChar['4'] = u'\u'
reverseChar['5'] = u'\u0F4A'
reverseChar['6'] = u'\u'
reverseChar['7'] = u'\u'
reverseChar['9'] = u'\u'
reverseChar[','] = u'\u02BD'
reverseChar['@'] = u'\u13A7'
'''
for key in reverseChar:
    print key, reverseChar[key].encode('utf-8')

message = ''.join(sys.argv[1:])[::-1]


